apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: awx-operator
    releaseName: awx-operator
    repo: https://ansible.github.io/awx-operator/
    version: 0.17.1
    includeCRDs: true

