apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: awx-operator/awx-operator
    releaseName: awx-operator
    repo: https://ansible.github.io/awx-operator/
    version: 2.10.2
    includeCRDs: true
resources:
- namespace.yaml
