apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- git@github.com:ansible/awx-resource-operator.git/config/default
images:
- name: quay.io/ansible/awx-resource-operator
  newName: quay.io/ansible/awx-resource-operator
  newTag: latest
namespace: awx-resource-operator
