apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/ansible/awx-resource-operator/devel/config/default/kustomization.yaml
images:
- name: quay.io/ansible/awx-resource-operator
  newName: quay.io/ansible/awx-resource-operator
  newTag: latest
namespace: awx-resource-operator
